rpc:
  mode: near-testnet
  mode-type: near
  title: "NEAR Testnet"
  title-color: "#2E8B57"
  get-safe-blocks: true
  get-finalized-blocks: true
  anomaly-detection:
    high-latency-ms: 1500
    long-delay-block-count: 20
    stale-block-threshold-ms: 5000
    block-gap-threshold: 10
  requests:
    optimal-poll-interval-ms: 1000
    sparse-poll-interval-ms: 30000
  nodes:
    - name: rpc.testnet.near.org
      http: https://rpc.testnet.near.org
    - name: publicnode.com
      http: https://near-testnet-rpc.publicnode.com
      requests: sparse
