rpc:
  mode: bnb-testnet
  mode-type: cosmos
  title: "BNB Smart Chain Testnet (Chapel)"
  title-color: "#f0b90b"
  get-safe-blocks: false
  get-finalized-blocks: true
  scale-change-ms: 250
  scale-max-ms: 15000
  anomaly-detection:
    high-latency-ms: 1000
    long-delay-block-count: 30
    stale-block-threshold-ms: 10000
    block-gap-threshold: 20
  requests:
    optimal-poll-interval-ms: 1000
    sparse-poll-interval-ms: 30000
  nodes:
    - name: bnbchain.org
      http: https://data-seed-prebsc-1-s1.bnbchain.org:8545
    - name: publicnode.com
      http: https://bsc-testnet-rpc.publicnode.com
      ws: wss://bsc-testnet-rpc.publicnode.com
      requests: sparse
    - name: drpc.org
      http: https://bsc-testnet.drpc.org
      ws: wss://bsc-testnet.drpc.org
      requests: sparse
    - name: BlastAPI
      http: https://bsc-testnet.public.blastapi.io
      ws: wss://bsc-testnet.public.blastapi.io
      requests: sparse
